### ISSUE TITLE
Python 3.9 support dropped

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-dask#254]
I see that in the latest release, Python 3.9 support has been dropped.
@ValentinaHutter could you point out the reason? Maybe we should specify clearly which Python versions are supported also in the Readme.

**Comment by clausmichele** [comment]
`odc-geo` officially supports Python>=3.8: https://pypi.org/project/odc-geo/

If there's an issue with a specific package, I would instead open an issue here mentioning that (so that someone else could also try to find a solution) and in the corresponding `odc-geo` repository instead of dropping completely the support without any open discussion.

**Comment by ValentinaHutter** [comment]
`odc-geo` uses python3.10 for the testing. There will be a fix for python3.9 in the next release. If there is a need to reactivate python3.9, we can do so once the release is available. 
Still, since the end of the support lifecycle for python3.9 is coming closer and we do not want to limit the repo to old versions of our dependencies, it is possible, that issues with dependencies will come up again. 

Is there an urgent need to reactivate the python3.9 support?

**Comment by clausmichele** [comment]
On my side there is no urgent need, but again, in my opinion this kind of change should be reported and discussed, since it's not just us (EODC and Eurac) using this package at the moment. I'll have to adapt the docs for the client side processing here: https://open-eo.github.io/openeo-python-client/cookbook/localprocessing.html mentioning that Python 3.10 is required.

**Comment by clausmichele** [comment]
Closing this, since even `xarray` and `numpy` will drop support for Python 3.9 soon: https://github.com/pydata/xarray/pull/8937
