### ISSUE TITLE
`aggregate_spatial` calls reducer separately on spatial dimensions

### ISSUE THREAD

**Issue by clausmichele** [Open-EO/openeo-processes-dask#26]
Same issue that was present in the old repo: https://github.com/Open-EO/openeo-processes-python/issues/180

https://github.com/Open-EO/openeo-processes-dask/blob/8f718b8ba43b84180ab6995644929f68b95d6b4c/openeo_processes_dask/process_implementations/cubes/aggregate.py#L113

**Comment by LukeWeidenwalker** [comment]
Thanks for porting the issue! True, this is still a problem, I've never resolved this because I expected that we'll probably change aggregate_spatial quite a bit once we get into UC8 optimisation again. That's on the horizon soon, so I'm inclined to ignore this for a little longer!

Should also be easier to address once https://github.com/Open-EO/openeo-processes-dask/pull/21 is merged, because that allows the subprocesses to work on the flattened arrays if nothing else is specified!

**Comment by clausmichele** [comment]
A new version of `aggregate_spatial` is here: https://github.com/Open-EO/openeo-processes-dask/pull/194
